import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <header>
          <h1>Aprendendo next js</h1>

          <ul className="flex" >
            <li className="mr-4"><a href="/">Home</a></li>
            <li className="mr-4"><a href="/fiap">FIAP</a></li>
            <li className="mr-4"><a href="/contato">Contato</a></li>
          </ul>
        </header>
        {children}</body>
    </html>
  );
}
