SELECT * FROM TABELA_DE_CLIENTES WHERE idade > 22;

SELECT * FROM TABELA_DE_CLIENTES WHERE idade < 22; 

SELECT * FROM TABELA_DE_CLIENTES WHERE idade != 22;

SELECT * FROM tabela_de_clientes WHERE DATA_DE_NASCIMENTO > TO_DATE('14/11/1995', 'DD/MM/YYYY'); 

SELECT * FROM TABELA_DE_CLIENTES WHERE IDADE BETWEEN 18 AND 22;



SELECT * FROM TABELA_DE_PRODUTOS WHERE SABOR = 'Manga' AND TAMANHO = '470 ml';

SELECT * FROM TABELA_DE_PRODUTOS WHERE NOT (SABOR = 'Manga' AND TAMANHO = '470 ml');

SELECT * FROM TABELA_DE_PRODUTOS WHERE NOT (SABOR = 'Manga' OR TAMANHO = '470 ml');


SELECT * FROM TABELA_DE_PRODUTOS WHERE SABOR = 'Manga' OR SABOR = 'Laranja' or sabor = 'Melancia';

SELECT * FROM TABELA_DE_PRODUTOS WHERE SABOR IN('Manga','Laranja', 'Melancia');

SELECT * FROM TABELA_DE_CLIENTES WHERE CIDADE IN('Rio de Janeiro',  'Sao Paulo') AND(IDADE BETWEEN 20 AND 25);


SELECT * FROM TABELA_DE_PRODUTOS WHERE SABOR LIKE '%Morango%';


SELECT * FROM TABELA_DE_CLIENTES WHERE NOME LIKE '%Silva%';

SELECT DISTINCT EMBALAGEM FROM TABELA_DE_PRODUTOS;

SELECT * FROM TABELA_DE_CLIENTES WHERE ROWNUM <= 4;

SELECT * FROM TABELA_DE_CLIENTES ORDER BY IDADE ASC;


SELECT * FROM TABELA_DE_CLIENTES;

SELECT CIDADE, SUM(IDADE) FROM TABELA_DE_CLIENTES 
GROUP BY CIDADE ORDER BY CIDADE;

SELECT CIDADE, SUM(LIMITE_DE_CREDITO), SUM(IDADE) 
FROM TABELA_DE_CLIENTES 
GROUP BY CIDADE;

SELECT EMBALAGEM, MAX(PRECO_DE_LISTA) 
FROM TABELA_DE_PRODUTOS 
GROUP BY EMBALAGEM;

SELECT EMBALAGEM, COUNT(*) AS "NUMERO DE PRODUTOS" 
FROM TABELA_DE_PRODUTOS 
WHERE SABOR = 'Laranja' 
GROUP BY EMBALAGEM 
ORDER BY EMBALAGEM;

SELECT SABOR, SUM(PRECO_DE_LISTA)
FROM TABELA_DE_PRODUTOS
GROUP BY SABOR;

SELECT TAMANHO, SABOR, AVG(PRECO_DE_LISTA) 
FROM TABELA_DE_PRODUTOS
GROUP BY TAMANHO, SABOR
ORDER BY TAMANHO;

SELECT EMBALAGEM, SUM(PRECO_DE_LISTA) AS "TOTAL POR EMBALAGEM"
FROM TABELA_DE_PRODUTOS
GROUP BY EMBALAGEM
HAVING SUM(PRECO_DE_LISTA) < 100
ORDER BY "TOTAL POR EMBALAGEM" DESC;

SELECT * FROM TABELA_DE_VENDEDORES;

SELECT MATRICULA, COUNT(*) AS "NUMERO DE NOTAS" FROM NOTAS_FISCAIS GROUP BY MATRICULA;

SELECT NOTAS_FISCAIS.MATRICULA, TABELA_DE_VENDEDORES.NOME, COUNT(*)
FROM NOTAS_FISCAIS 
INNER JOIN TABELA_DE_VENDEDORES
ON NOTAS_FISCAIS.MATRICULA = TABELA_DE_VENDEDORES.MATRICULA
GROUP BY NOTAS_FISCAIS.MATRICULA, TABELA_DE_VENDEDORES.NOME;

SELECT TC.CPF AS CPF_DO_CADASTRO, TC.NOME AS NOME_DO_CLIENTE, NF.CPF AS CPF_NOTAS_FISCAIS
FROM TABELA_DE_CLIENTES TC
INNER JOIN NOTAS_FISCAIS NF
ON TC.CPF = NF.CPF;













