SELECT * FROM EMPLOYEES;

SELECT * FROM DEPARTMENTS;

SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME FROM EMPLOYEES;

SELECT * FROM JOB_HISTORY WHERE START_DATE > TO_DATE('01-JAN-21', 'DD-MM-YY');

SELECT * FROM EMPLOYEES WHERE SALARY > 5000;

SELECT * FROM COUNTRIES WHERE COUNTRY_NAME LIKE('U%');

SELECT * FROM LOCATIONS WHERE CITY = 'NEW YORK';

SELECT JOB_ID, JOB_TITLE FROM JOBS WHERE MIN_SALARY < 3000;

SELECT * FROM DEPARTMENTS WHERE MANAGER_ID IS NULL ;

SELECT * FROM REGIONS WHERE REGION_NAME != 'Europe';

SELECT EMPLOYEE_ID, (FIRST_NAME|| ' ' ||LAST_NAME) FROM EMPLOYEES WHERE SALARY > (SELECT AVG(SALARY) FROM EMPLOYEES);

SELECT DEPARTMENT_ID DEPARTAMENTO, ROUND(AVG(SALARY),2) MEDIA_SALARIO FROM EMPLOYEES GROUP BY DEPARTMENT_ID ORDER BY DEPARTMENT_ID ASC, 2 DESC;

