[8:13 AM] Mauricio Vieira Pereira
SELECT 'DROP TABLE ' || TABLE_NAME || ' CASCADE CONSTRAINTS; ' FROM USER_TABLES
 
DROP TABLE BAIRRO CASCADE CONSTRAINTS; 

DROP TABLE CARGO CASCADE CONSTRAINTS; 

DROP TABLE CIDADE CASCADE CONSTRAINTS; 

DROP TABLE CLIENTE CASCADE CONSTRAINTS; 

DROP TABLE CLIENTE_FISICO CASCADE CONSTRAINTS; 

DROP TABLE CLIENTE_JURICA CASCADE CONSTRAINTS; 

DROP TABLE DEPARTAMENTO CASCADE CONSTRAINTS; 

DROP TABLE DEPARTMENTS CASCADE CONSTRAINTS; 

DROP TABLE ENDERECO_CLIENTE CASCADE CONSTRAINTS; 

DROP TABLE ESTADO CASCADE CONSTRAINTS; 

DROP TABLE ESTADO_CIVIL CASCADE CONSTRAINTS; 

DROP TABLE FUNCIONARIO CASCADE CONSTRAINTS; 

DROP TABLE GENERO CASCADE CONSTRAINTS; 

DROP TABLE ITEM_PEDIDO CASCADE CONSTRAINTS; 

DROP TABLE ITEM_VENDA CASCADE CONSTRAINTS; 

DROP TABLE JOBS CASCADE CONSTRAINTS; 

DROP TABLE JOB_GRADES CASCADE CONSTRAINTS; 

DROP TABLE JOB_HISTORY CASCADE CONSTRAINTS; 

DROP TABLE LOCATIONS CASCADE CONSTRAINTS; 

DROP TABLE PAIS CASCADE CONSTRAINTS; 

DROP TABLE PEDIDO CASCADE CONSTRAINTS; 

DROP TABLE PRODUTO CASCADE CONSTRAINTS; 

DROP TABLE REGIAO CASCADE CONSTRAINTS; 

DROP TABLE REGIONS CASCADE CONSTRAINTS; 

DROP TABLE RELATION_15 CASCADE CONSTRAINTS; 

DROP TABLE RELATION_16 CASCADE CONSTRAINTS; 

DROP TABLE TB_FORNECEDOR CASCADE CONSTRAINTS; 

DROP TABLE TB_PRODUTO CASCADE CONSTRAINTS; 

DROP TABLE TIPO CASCADE CONSTRAINTS; 

DROP TABLE TIPO_CLIENTE CASCADE CONSTRAINTS; 

DROP TABLE TIPO_PRODUTO CASCADE CONSTRAINTS; 

DROP TABLE TIPO_SEXO CASCADE CONSTRAINTS; 

DROP TABLE T_BAIRRO CASCADE CONSTRAINTS; 

DROP TABLE T_CARGO CASCADE CONSTRAINTS; 

DROP TABLE T_CIDADE CASCADE CONSTRAINTS; 

DROP TABLE T_CLIENTE CASCADE CONSTRAINTS; 

DROP TABLE T_DEPARTAMENTO CASCADE CONSTRAINTS; 

DROP TABLE T_ENDERECO_CLIENTE CASCADE CONSTRAINTS; 

DROP TABLE T_ESTADO CASCADE CONSTRAINTS; 

DROP TABLE T_ESTADO_CIVIL CASCADE CONSTRAINTS; 

DROP TABLE T_FUNCIONARIO CASCADE CONSTRAINTS; 

DROP TABLE T_ITEM_VENDA CASCADE CONSTRAINTS; 

DROP TABLE T_MARCA CASCADE CONSTRAINTS; 

DROP TABLE T_PAIS CASCADE CONSTRAINTS; 

DROP TABLE T_PRODUTO CASCADE CONSTRAINTS; 

DROP TABLE T_REGIAO CASCADE CONSTRAINTS; 

DROP TABLE T_TIPO_CLIENTE CASCADE CONSTRAINTS; 

DROP TABLE T_TIPO_PRODUTO CASCADE CONSTRAINTS; 

DROP TABLE T_TIPO_SEXO CASCADE CONSTRAINTS; 

DROP TABLE T_VENDA CASCADE CONSTRAINTS;
[8:13 AM] Mauricio Vieira Pereira
-- Generated by Oracle SQL Developer Data Modeler 23.1.0.087.0806

--   at:        2024-02-19 07:51:36 BRT

--   site:      Oracle Database 21c

--   type:      Oracle Database 21c
 
 
-- predefined type, no DDL - MDSYS.SDO_GEOMETRY
 
-- predefined type, no DDL - XMLTYPE
 
CREATE TABLE bairro (

    cod_bairro        NUMBER NOT NULL,

    nome              VARCHAR2(30),

    cidade_cod_cidade NUMBER NOT NULL

);
 
ALTER TABLE bairro ADD CONSTRAINT bairro_pk PRIMARY KEY ( cod_bairro );
 
CREATE TABLE cargo (

    cod_cargo NUMBER NOT NULL,

    nome      VARCHAR2(30)

);
 
ALTER TABLE cargo ADD CONSTRAINT cargo_pk PRIMARY KEY ( cod_cargo );
 
CREATE TABLE cidade (

    cod_cidade        NUMBER NOT NULL,

    nome              VARCHAR2(30),

    estado_cod_estado NUMBER NOT NULL

);
 
ALTER TABLE cidade ADD CONSTRAINT cidade_pk PRIMARY KEY ( cod_cidade );
 
CREATE TABLE cliente (

    cod_cliente                   NUMBER NOT NULL,

    nome                          VARCHAR2(50),

    endereco_cliente_cod_endereco NUMBER NOT NULL

);
 
ALTER TABLE cliente ADD CONSTRAINT cliente_pk PRIMARY KEY ( cod_cliente );
 
CREATE TABLE cliente_fisico (

    cod_cli_fisico      NUMBER NOT NULL,

    cpf                 NUMBER,

    cliente_cod_cliente NUMBER NOT NULL,

    genero_cod_genero   NUMBER NOT NULL

);
 
ALTER TABLE cliente_fisico

    ADD CONSTRAINT cliente_fisico_pk PRIMARY KEY ( cod_cli_fisico,

                                                   cliente_cod_cliente,

                                                   genero_cod_genero );
 
CREATE TABLE cliente_jurica (

    cod_pessoa_ju       NUMBER NOT NULL,

    cnpj                NUMBER,

    ie                  NUMBER,

    cliente_cod_cliente NUMBER NOT NULL

);
 
ALTER TABLE cliente_jurica ADD CONSTRAINT cliente_jurica_pk PRIMARY KEY ( cod_pessoa_ju );
 
CREATE TABLE endereco_cliente (

    cod_endereco      NUMBER NOT NULL,

    numero            NUMBER,

    cep               NUMBER,

    referencia        VARCHAR2(200),

    bairro_cod_bairro NUMBER NOT NULL

);
 
ALTER TABLE endereco_cliente ADD CONSTRAINT endereco_cliente_pk PRIMARY KEY ( cod_endereco );
 
CREATE TABLE estado (

    cod_estado    NUMBER NOT NULL,

    nome_estado   VARCHAR2(30),

    pais_cod_pais NUMBER NOT NULL

);
 
ALTER TABLE estado ADD CONSTRAINT estado_pk PRIMARY KEY ( cod_estado );
 
CREATE TABLE funcionario (

    cod_funcionario             NUMBER NOT NULL,

    nome                        VARCHAR2(30),

    data_cadastro               DATE,

    cargo_cod_cargo             NUMBER NOT NULL,

    funcionario_cod_funcionario NUMBER

);
 
CREATE UNIQUE INDEX funcionario__idx ON

    funcionario (

        cargo_cod_cargo

    ASC );
 
ALTER TABLE funcionario ADD CONSTRAINT funcionario_pk PRIMARY KEY ( cod_funcionario );
 
CREATE TABLE genero (

    cod_genero NUMBER NOT NULL,

    descricao  VARCHAR2(30)

);
 
ALTER TABLE genero ADD CONSTRAINT genero_pk PRIMARY KEY ( cod_genero );
 
CREATE TABLE item_pedido (

    quantidade          NUMBER(10),

    valor_unitario      NUMBER(10),

    valor_total         NUMBER(10),

    pedido_cod_pedido   NUMBER NOT NULL,

    produto_cod_produto NUMBER NOT NULL

);
 
ALTER TABLE item_pedido ADD CONSTRAINT item_pedido_pk PRIMARY KEY ( pedido_cod_pedido,

                                                                    produto_cod_produto );
 
CREATE TABLE pais (

    cod_pais NUMBER NOT NULL,

    nome     VARCHAR2(30)

);
 
ALTER TABLE pais ADD CONSTRAINT pais_pk PRIMARY KEY ( cod_pais );
 
CREATE TABLE pedido (

    cod_pedido                         NUMBER NOT NULL,

    data                               DATE,

    cliente_fisico_cod_cli_fisico      NUMBER NOT NULL, 

--  ERROR: Column name length exceeds maximum allowed length(30) 

    cliente_fisico_cliente_cod_cliente NUMBER NOT NULL, 

--  ERROR: Column name length exceeds maximum allowed length(30) 

    cliente_fisico_genero_cod_genero   NUMBER NOT NULL,

    funcionario_cod_funcionario        NUMBER NOT NULL,

    cliente_jurica_cod_pessoa_ju       NUMBER NOT NULL,

    funcionario_cod_funcionario2       NUMBER NOT NULL

);
 
CREATE UNIQUE INDEX pedido__idx ON

    pedido (

        funcionario_cod_funcionario

    ASC );
 
CREATE UNIQUE INDEX pedido__idxv1 ON

    pedido (

        funcionario_cod_funcionario2

    ASC );
 
ALTER TABLE pedido ADD CONSTRAINT pedido_pk PRIMARY KEY ( cod_pedido );
 
CREATE TABLE produto (

    cod_produto   NUMBER NOT NULL,

    descricao     VARCHAR2(30),

    tipo_cod_tipo NUMBER NOT NULL

);
 
CREATE UNIQUE INDEX produto__idx ON

    produto (

        tipo_cod_tipo

    ASC );
 
ALTER TABLE produto ADD CONSTRAINT produto_pk PRIMARY KEY ( cod_produto );
 
CREATE TABLE tipo (

    cod_tipo  NUMBER NOT NULL,

    descricao VARCHAR2(30)

);
 
ALTER TABLE tipo ADD CONSTRAINT tipo_pk PRIMARY KEY ( cod_tipo );
 
ALTER TABLE bairro

    ADD CONSTRAINT bairro_cidade_fk FOREIGN KEY ( cidade_cod_cidade )

        REFERENCES cidade ( cod_cidade );
 
ALTER TABLE cidade

    ADD CONSTRAINT cidade_estado_fk FOREIGN KEY ( estado_cod_estado )

        REFERENCES estado ( cod_estado );
 
ALTER TABLE cliente

    ADD CONSTRAINT cliente_endereco_cliente_fk FOREIGN KEY ( endereco_cliente_cod_endereco )

        REFERENCES endereco_cliente ( cod_endereco );
 
ALTER TABLE cliente_fisico

    ADD CONSTRAINT cliente_fisico_cliente_fk FOREIGN KEY ( cliente_cod_cliente )

        REFERENCES cliente ( cod_cliente );
 
ALTER TABLE cliente_fisico

    ADD CONSTRAINT cliente_fisico_genero_fk FOREIGN KEY ( genero_cod_genero )

        REFERENCES genero ( cod_genero );
 
ALTER TABLE cliente_jurica

    ADD CONSTRAINT cliente_jurica_cliente_fk FOREIGN KEY ( cliente_cod_cliente )

        REFERENCES cliente ( cod_cliente );
 
ALTER TABLE endereco_cliente

    ADD CONSTRAINT endereco_cliente_bairro_fk FOREIGN KEY ( bairro_cod_bairro )

        REFERENCES bairro ( cod_bairro );
 
ALTER TABLE estado

    ADD CONSTRAINT estado_pais_fk FOREIGN KEY ( pais_cod_pais )

        REFERENCES pais ( cod_pais );
 
ALTER TABLE funcionario

    ADD CONSTRAINT funcionario_cargo_fk FOREIGN KEY ( cargo_cod_cargo )

        REFERENCES cargo ( cod_cargo );
 
ALTER TABLE funcionario

    ADD CONSTRAINT funcionario_funcionario_fk FOREIGN KEY ( funcionario_cod_funcionario )

        REFERENCES funcionario ( cod_funcionario );
 
ALTER TABLE item_pedido

    ADD CONSTRAINT item_pedido_pedido_fk FOREIGN KEY ( pedido_cod_pedido )

        REFERENCES pedido ( cod_pedido );
 
ALTER TABLE item_pedido

    ADD CONSTRAINT item_pedido_produto_fk FOREIGN KEY ( produto_cod_produto )

        REFERENCES produto ( cod_produto );
 
ALTER TABLE pedido

    ADD CONSTRAINT pedido_cliente_fisico_fk FOREIGN KEY ( cliente_fisico_cod_cli_fisico,

                                                          cliente_fisico_cliente_cod_cliente,

                                                          cliente_fisico_genero_cod_genero )

        REFERENCES cliente_fisico ( cod_cli_fisico,

                                    cliente_cod_cliente,

                                    genero_cod_genero );
 
ALTER TABLE pedido

    ADD CONSTRAINT pedido_cliente_jurica_fkv1 FOREIGN KEY ( cliente_jurica_cod_pessoa_ju )

        REFERENCES cliente_jurica ( cod_pessoa_ju );
 
ALTER TABLE pedido

    ADD CONSTRAINT pedido_funcionario_fk FOREIGN KEY ( funcionario_cod_funcionario )

        REFERENCES funcionario ( cod_funcionario );
 
ALTER TABLE pedido

    ADD CONSTRAINT pedido_funcionario_fkv2 FOREIGN KEY ( funcionario_cod_funcionario2 )

        REFERENCES funcionario ( cod_funcionario );
 
ALTER TABLE produto

    ADD CONSTRAINT produto_tipo_fk FOREIGN KEY ( tipo_cod_tipo )

        REFERENCES tipo ( cod_tipo );
 
 
[8:14 AM] Mauricio Vieira Pereira
ALTER TABLE PRODUTO RENAME COLUMN TIPO_COD_TIPO TO COD_TIPO;
 
INSERT INTO PAIS (COD_PAIS, NOME) VALUES (1,'BRASIL');

COMMIT;
 
INSERT INTO PAIS (COD_PAIS, NOME) VALUES (2,'ARGENTINA');

COMMIT;
 
INSERT INTO PAIS (COD_PAIS, NOME) VALUES (3,'COLOMBIA');

COMMIT;
 
INSERT INTO PAIS (COD_PAIS, NOME) VALUES (4,'ESTADOS UNIDOS');

COMMIT;
 
INSERT INTO PAIS (COD_PAIS, NOME) VALUES (5,'VENEZUELA');

COMMIT;
 
INSERT INTO ESTADO (COD_ESTADO, NOME_ESTADO, COD_PAIS) VALUES (1, 'São Paulo', 1);

COMMIT;
 
INSERT INTO ESTADO (COD_ESTADO, NOME_ESTADO, COD_PAIS) VALUES (2, 'Minas Gerais', 1);

COMMIT;
 
INSERT INTO ESTADO (COD_ESTADO, NOME_ESTADO, COD_PAIS) VALUES (3, 'Rio de Janeiro', 1);

COMMIT;
 
INSERT INTO ESTADO (COD_ESTADO, NOME_ESTADO, COD_PAIS) VALUES (4, 'Bahia', 1);

COMMIT;
 
INSERT INTO ESTADO (COD_ESTADO, NOME_ESTADO, COD_PAIS) VALUES (5, 'Acre', 1);

COMMIT;
 
 
INSERT INTO ESTADO (COD_ESTADO, NOME_ESTADO, COD_PAIS) VALUES (6, 'Buenos Aires', 2);

COMMIT;
 
INSERT INTO ESTADO (COD_ESTADO, NOME_ESTADO, COD_PAIS) VALUES (7, 'Terra do Fogo', 2);

COMMIT;
 
INSERT INTO ESTADO (COD_ESTADO, NOME_ESTADO, COD_PAIS) VALUES (8, 'La Pampa', 2);

COMMIT;
 
INSERT INTO ESTADO (COD_ESTADO, NOME_ESTADO, COD_PAIS) VALUES (9, 'Chaco', 2);

COMMIT;
 
INSERT INTO ESTADO (COD_ESTADO, NOME_ESTADO, COD_PAIS) VALUES (10, 'Santa Cruz', 2);

COMMIT;
 
INSERT INTO ESTADO (COD_ESTADO, NOME_ESTADO, COD_PAIS) VALUES (11, 'Cesar', 3);

COMMIT;
 
INSERT INTO ESTADO (COD_ESTADO, NOME_ESTADO, COD_PAIS) VALUES (12, 'Magdalena', 3);

COMMIT;
 
INSERT INTO ESTADO (COD_ESTADO, NOME_ESTADO, COD_PAIS) VALUES (13, 'Sucre', 3);

COMMIT;
 
INSERT INTO ESTADO (COD_ESTADO, NOME_ESTADO, COD_PAIS) VALUES (14, 'Bolívar', 3);

COMMIT;
 
INSERT INTO ESTADO (COD_ESTADO, NOME_ESTADO, COD_PAIS) VALUES (15, 'La Guajira', 3);

COMMIT;
 
 
SELECT * FROM ESTADO;

DROP SEQUENCE SQ_PAIS;

CREATE SEQUENCE SQ_PAIS INCREMENT BY 1 START WITH 7 MAXVALUE 1000;

CREATE SEQUENCE SQ_ESTADO;

SELECT * FROM PAIS;

INSERT INTO PAIS (COD_PAIS, NOME) VALUES(SQ_PAIS.NEXTVAL, 'CHINA');
COMMIT;
 
INSERT INTO PAIS(COD_PAIS, NOME) VALUES (SQ_PAIS.NEXTVAL, 'CANADA')
        
INSERT INTO PAIS(COD_PAIS, NOME) VALUES (SQ_PAIS.NEXTVAL, 'PERU')

INSERT ALL 
    INTO PAIS (COD_PAIS, NOME) VALUES(9, 'COREIA DO NORTE')
    INTO PAIS (COD_PAIS, NOME) VALUES(10, 'COREIA DO SUL')
    INTO PAIS (COD_PAIS, NOME) VALUES(11, 'SUDÃO DO SUL')
SELECT * FROM DUAL;

INSERT ALL
    INTO CIDADE(COD_CIDADE, NOME, ESTADO_COD_ESTADO) VALUES (1, 'SAO PAULO', 1)
 
    INTO CIDADE(COD_CIDADE, NOME, ESTADO_COD_ESTADO) VALUES (2, 'SAO CAETANO', 1)
 
    INTO CIDADE(COD_CIDADE, NOME, ESTADO_COD_ESTADO) VALUES (3, 'SAO BERNARDO', 1)
 
    INTO CIDADE(COD_CIDADE, NOME, ESTADO_COD_ESTADO) VALUES (4, 'SANTO ANDRE', 1)
 
    INTO CIDADE(COD_CIDADE, NOME, ESTADO_COD_ESTADO) VALUES (5, 'DIADEMA', 1)
 
    INTO CIDADE(COD_CIDADE, NOME, ESTADO_COD_ESTADO) VALUES (6, 'NITEROI', 2)
 
    INTO CIDADE(COD_CIDADE, NOME, ESTADO_COD_ESTADO) VALUES (7, 'RIO DE JANEIRO', 2)
 
    INTO CIDADE(COD_CIDADE, NOME, ESTADO_COD_ESTADO) VALUES (7, 'BELFORD ROXO', 2)
 
    INTO CIDADE(COD_CIDADE, NOME, ESTADO_COD_ESTADO) VALUES (9, 'SAO GONÇALO', 2)
 
    INTO CIDADE(COD_CIDADE, NOME, ESTADO_COD_ESTADO) VALUES (10, 'DUQUE DE CAXIAS', 2)
 
    INTO CIDADE(COD_CIDADE, NOME, ESTADO_COD_ESTADO) VALUES (11, 'VITORIA DA CONQUISTA', 3)
 
    INTO CIDADE(COD_CIDADE, NOME, ESTADO_COD_ESTADO) VALUES (12, 'PAULO AFONSO', 3)
 
    INTO CIDADE(COD_CIDADE, NOME, ESTADO_COD_ESTADO) VALUES (13, 'BARREIRAS', 3)
 
    INTO CIDADE(COD_CIDADE, NOME, ESTADO_COD_ESTADO) VALUES (14, 'ITABUNA', 3)
 
    INTO CIDADE(COD_CIDADE, NOME, ESTADO_COD_ESTADO) VALUES (15, 'SALVADOR', 3)
 
    INTO CIDADE(COD_CIDADE, NOME, ESTADO_COD_ESTADO) VALUES (16, 'BELO HORIZONTE', 4)
     
    INTO CIDADE(COD_CIDADE, NOME, ESTADO_COD_ESTADO) VALUES (17, 'PASSA QUATRO', 4)
     
    INTO CIDADE(COD_CIDADE, NOME, ESTADO_COD_ESTADO) VALUES (18, 'PASSA VINTE', 4)
     
    INTO CIDADE(COD_CIDADE, NOME, ESTADO_COD_ESTADO) VALUES (19, 'ITANHANDU', 4)
     
    INTO CIDADE(COD_CIDADE, NOME, ESTADO_COD_ESTADO) VALUES (20, 'UBERLANDIA', 4)
     
    INTO CIDADE(COD_CIDADE, NOME, ESTADO_COD_ESTADO) VALUES (21, 'MANAUS', 5)
     
    INTO CIDADE(COD_CIDADE, NOME, ESTADO_COD_ESTADO) VALUES (22, 'MANACAPURU', 5)
     
    INTO CIDADE(COD_CIDADE, NOME, ESTADO_COD_ESTADO) VALUES (23, 'TEFE', 5)
     
    INTO CIDADE(COD_CIDADE, NOME, ESTADO_COD_ESTADO) VALUES (24, 'TABATINGA', 5)
     
    INTO CIDADE(COD_CIDADE, NOME, ESTADO_COD_ESTADO) VALUES (25, 'IRANDUBA', 5)
SELECT * FROM DUAL;

DELETE FROM ESTADO WHERE COD_ESTADO = 5;

SELECT * FROM PAIS;
SELECT * FROM ESTADO;
SELECT * FROM CIDADE;







 