SELECT ABS(-10) AS VALOR_ABSOLUTO FROM DUAL;

SELECT SIGN(-10) AS SINAL_NUMERO FROM DUAL;

SELECT ROUND(15.78) AS NUMERO_ARREDONDADO FROM DUAL;

SELECT TRUNC(15.78) AS NUMERO_TRUNCADO FROM DUAL;

SELECT CEIL(15.2) AS NUMERO_ARREDONDADO_PARA_CIMA FROM DUAL;

SELECT FLOOR(15.9) AS NUMERO_ARREDONDADO_PARA_CIMA FROM DUAL;


SELECT MOD(15, 4) AS RESTO_DIVISAO FROM DUAL;

SELECT SQRT(16) AS RAIZ_QUADRADA FROM DUAL;

SELECT LOG(10, 100) AS LGARITIMO_BASE10 FROM DUAL;

SELECT EXP(2) AS EXPONENCIAL FROM DUAL;


SELECT TO_NUMBER('123.65') AS NUMERO_CONVERTIDO FROM DUAL;

SELECT TO_CHAR(123.45) AS STRING_CONVERTIDA FROM DUAL;

SELECT TO_CHAR(12345.45, '999,999.99') AS STRING_CONVERTIDA FROM DUAL;


SELECT LTRIM(JOB_TITLE) FROM JOBS;
SELECT TRIM(FIRST_NAME) FROM EMPLOYEES;
SELECT TRIM(LAST_NAME) FROM EMPLOYEES;
SELECT LPAD(JOB_TITLE, 20, '*') FROM JOBS;
SELECT RPAD(FIRST_NAME, 15, '-') FROM EMPLOYEES;

--LISTA EXERCICIOS

SELECT ROUND(SALARY) FROM EMPLOYEES 
WHERE department_id = 30 
ORDER BY SALARY; 

SELECT TRIM(LAST_NAME) FROM EMPLOYEES 
WHERE department_id = 50 
ORDER BY LAST_NAME;

SELECT to_char(hire_date, 'DD/MM/YYYY') 
AS data_formatada FROM employees 
WHERE department_id = 20 
ORDER BY data_formatada;

SELECT AVG(SALARY) FROM EMPLOYEES 
WHERE DEPARTMENT_ID = 60;

SELECT 

