SELECT * FROM EMPLOYEES E
WHERE E.DEPARTMENT_ID = (SELECT DEPARTMENT_ID
FROM DEPARTMENTS D 
WHERE UPPER(D.DEPARTMENT_NAME) = 'MARKETING')
ORDER BY E.EMPLOYEE_ID;


SELECT
   E.EMPLOYEE_ID,
   E.FIRST_NAME || ' ' || E.LAST_NAME AS NOME_FUNCIONARIO,
   E.MANAGER_ID,
   (SELECT M.FIRST_NAME || ' ' || M.LAST_NAME
   FROM EMPLOYEES M
   WHERE E.MANAGER_ID = M.EMPLOYEE_ID) AS NOME_GERENTE
FROM EMPLOYEES E
WHERE ( E.DEPARTMENT_ID, E.FIRST_NAME ) IN
      (SELECT M2.DEPARTMENT_ID,
       M2.FIRST_NAME
       FROM EMPLOYEES M2
       WHERE E.MANAGER_ID = M2.EMPLOYEE_ID)
ORDER BY E.EMPLOYEE_ID;


CREATE TABLE TABELA_FUNCIONARIO_NOME AS SELECT
   E.EMPLOYEE_ID,
   E.FIRST_NAME || ' ' || E.LAST_NAME AS NOME_FUNCIONARIO,
   E.MANAGER_ID,
   (SELECT M.FIRST_NAME || ' ' || M.LAST_NAME
   FROM EMPLOYEES M
   WHERE E.MANAGER_ID = M.EMPLOYEE_ID) AS NOME_GERENTE
FROM EMPLOYEES E
WHERE ( E.DEPARTMENT_ID, E.FIRST_NAME ) IN
      (SELECT M2.DEPARTMENT_ID,
       M2.FIRST_NAME
       FROM EMPLOYEES M2
       WHERE E.MANAGER_ID = M2.EMPLOYEE_ID)
       AND 1=2
ORDER BY E.EMPLOYEE_ID;

SELECT * FROM TABELA_FUNCIONARIO_NOME;

CREATE TABLE PROMOCOES(
PROMOTION_EMPLOYEE_ID NUMBER(6,0),
EMPLOYEE_ID NUMBER(6,0) NOT NULL,
DT_PROMOTION DATE NOT NULL);

INSERT INTO PROMOCOES (EMPLOYEE_ID, DT_PROMOTION)
SELECT E. EMPLOYEE_ID,
SYSDATE FROM EMPLOYEES E 
JOIN JOB_HISTORY J ON E.EMPLOYEE_ID = J.EMPLOYEE_ID
WHERE E.JOB_ID = J.JOB_ID
AND MONTHS_BETWEEN(SYSDATE, J.END_DATE) > 12
ORDER BY E.EMPLOYEE_ID;

SELECT SUBQUERY.FIRST_NAME,
SUBQUERY.JOB_ID,
SUBQUERY.SALARY,
SUBQUERY.MEDIA_SALARIO_CARGO
FROM (SELECT E.FIRST_NAME,
E.JOB_ID,
E.SALARY,
(SELECT AVG(E.SALARY)
FROM EMPLOYEES E2 
WHERE E.JOB_ID = E2.JOB_ID
GROUP BY JOB_ID) MEDIA_SALARIO_CARGO
FROM EMPLOYEES E) SUBQUERY
WHERE SUBQUERY.SALARY > SUBQUERY.MEDIA_SALARIO_CARGO;

UPDATE EMPLOYEES E
SET SALARY = (SELECT MAX(SALARY)
FROM EMPLOYEES E2
WHERE E2.JOB_ID = E.JOB_ID);


SELECT * FROM EMPLOYEES E
WHERE E.SALARY > (SELECT AVG(E2.SALARY)
FROM EMPLOYEES E2
WHERE E2.DEPARTMENT_ID = 50);